title: Rinie's Blog
description: Weak link willing to learn from actual Use feedback
url: "https://rinie.github.io"
theme: minima

minima:
  skin: classic

author:
  name: Rinie Kervel

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - "*.sh"
